spring:
  cloud:
    gateway:
      routes:
        - id: google
          uri: http://google.com
          predicates:
            - Path=/drive
        - id: facebook
          uri: http://facebook.com
          predicates:
            - Path=/groups
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/products/**